accounts/urls.py
from django.urls import path
from accounts.views import signup
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    AccountListView,
    ExpenseCategoryCreateView,
    ExpenseCategoryListView,
    ReceiptCreateView,
    ReceiptListView,
    AccountCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("accounts/", AccountListView.as_view(), name="receipt_accounts"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_categories",
    ),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="create_account",
    ),
]

# final

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self) -> str:
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self) -> str:
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        User, related_name="receipts", on_delete=models.CASCADE, null=True
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from .models import Account, ExpenseCategory, Receipt
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect


# Create your views here.

# Protect the list view for the Receipt model
# so that only a person who has logged in can access it. (LoginRequired)
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    template_name = "receipts/create.html"

    # a method that assigns the current user to a User property
    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = (
            self.request.user
        )  # use 'purchaser' because it's the foreign key with User in it
        item.save()
        return redirect("receipts/list.html")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    fields = ["name"]
    template_name = "categories/create.html"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("/receipts/categories/")


class AccountCreateView(CreateView):
    model = Account
    fields = ["name", "number"]
    template_name = "accounts/create.html"

receipts/templates/accounts/create.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>Create Account</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<main>
    <div>
        <h1>My Accounts</h1>
        {{receipts.all}}
        <table>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of receipt</th>
            </tr>
            <tbody>
                {% for account in account_list %}
                <tr>
                    <td>{{account.name}}</td>
                    <td>{{account.number}}</td>
                    <td>{{account.receipts.all | length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>

{% endblock content %}

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Expenses: the Web App!</title>
  
</head>

<body>
  <header>
    <nav>
      <ul>
        {% if user.is_staff %}
        <li>
          <a href="{% url 'admin:index' %}">Admin</a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
        {% endif %}
        {% if user.is_authenticated == False %}
        <li>
          <a href="{% url 'signup' %}">Signup</a>
          <a href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
        <li>
          <a href="{% url 'list_categories' %}">Categories List</a>
        </li>
        <li>
          <a href="{% url "receipt_accounts" %}">Receipt Accounts</a>
        </li>
        <li>
          <a href="{% url "create_account" %}">Create a Receipt Account</a>
        </li>
        <li>
          <a href="{% url "create_receipt" %}">Create a Receipt</a>
        </li>
      </ul>
    </nav>
    {% block pagination %}
    {% endblock pagination %}
  </header>
  {% block content %}
  {% endblock content %}
</body>

</html>

receipts/templates/categories/create.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>Create Category</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

receipts/templates/categories/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<body>
    <main>
        <div>
            <a href="{% url 'create_categories' %}">Create New Category</a>
        </div>
        <div>
            <h1>My Categories</h1>
            {{expensecategory.all}}
            <table>
                <tr>
                    <th>Name</th>
                    <th>Number of Receipts</th>
                </tr>
                <tbody>
                    {% for item in expensecategory_list %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.receipts.all | length }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}
{% block content %}
<body>
    <main>
        <div>
            <form method="post">
                <h1>Create Receipt</h1>
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>    
</body>
</html>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>
        <div>
            <h1>My Receipts</h1>
            {{receipts.all}}
            <table>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
                <tbody>
                    {% for receipt in receipt_list %}
                    <tr>
                        <td>{{receipt.vendor}}</td>
                        <td>{{receipt.total}}</td>
                        <td>{{receipt.tax}}</td>
                        <td>{{receipt.date|date:'d-m-Y'}}</td>
                        <td>{{receipt.category}}</td>
                        <td>{{receipt.account}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
 {% endblock content %}